insert into person values(1,'Wenqi','Chinese');
insert into person values(2,'Vinci','Italian');
insert into person values(3,'Miwako','Japanese');
insert into person values(4,'Fuling','Chinese');
insert into person values(5,'Daluo','Chinese');
insert into person values(6,'Silva','Spanish');
insert into person values(7,'Carol','English');
insert into person values(8,'Lucy','English');
insert into person values(9,'Kiki','Japanese');