package com.wenqi.bootwebdemo.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.wenqi.bootwebdemo.dao.JFYRepo;
import com.wenqi.bootwebdemo.model.Item;
import com.wenqi.bootwebdemo.model.Response;
import com.wenqi.bootwebdemo.util.JsonUtility;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;


// Deal with the received json
@Service
public class JFYService {
    @Autowired
    JFYRepo jfyRepo;

    public String storeResponse(HttpResponse<JsonNode> response) {
        ObjectMapper objectMapper = new ObjectMapper();
        JSONObject responseBody = response.getBody().getObject();
        // Mapping to Response object. responseObj can be further extracted
        // Here we are not using this.
        try {
            Response responseObj = getResponseObject(responseBody);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
        // Mapping to Item objects from "result" field
        JSONArray results = responseBody.getJSONArray("result");
        List<Item> items = extractProperties(results);
        jfyRepo.writeToDbWithTemplate(items);  // Now db stores my Items object
        jfyRepo.writeToJson(items); // File I/O experiment. Not used further.

        // Item objects in JSON string format are returned to controller
        String itemJsonStr = "";
        try {
            itemJsonStr = objectMapper.writeValueAsString(items);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
        return itemJsonStr;
    }

    /**
     * Map HTTP response body to the Response class which is generated by createClassFromJson
     * method during a previous successful call.
     *
     * @param responseBodyJson
     * @return a Response object
     * @throws JsonProcessingException
     */
    private Response getResponseObject(JSONObject responseBodyJson) throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        return objectMapper.readValue(responseBodyJson.toString(), Response.class);
    }

    private List<Item> extractProperties(JSONArray results) {
        List<Item> itemList = new ArrayList<Item>();
        for (Object result : results) {
            JSONObject obj = (JSONObject) result;
            // Check if type is item, if so cast to Item Object
            if (!obj.getString("type").equals("item")) {
                continue;
            }
            // Would be a good practice to keep the field name consistent
            // to avoid misunderstandings or confusions
            // Further improvements: Use ObjectMapper and
            // setup @JsonIgnoreProperties(ignoreUnknown = true) for Item class
            long itemId = obj.getLong("itemId");
            String itemTitle = obj.getString("itemTitle");
            double itemPrice = Double.parseDouble(obj.getString("itemPrice"));
            int itemSoldCnt = obj.getInt("itemSoldCnt");
            int stockAvailable = Integer.parseInt(obj.getString("stockAvailable"));
            String itemUrl = obj.getString("itemUrl");
            long shopId = obj.getLong("shopId");

            Item item = new Item(itemId, itemTitle, itemPrice, itemSoldCnt, stockAvailable, itemUrl, shopId);
            itemList.add(item);
        }
        return itemList;
    }

    /**
     * Create a java class according to the input JSON object structure.
     */
    public void createClassFromJson(JSONObject object) {
        String packageName = "com.wenqi.bootwebdemo.model";
        String basePath = "src/main/resources";
        String jsonPath = basePath + File.separator + "response.json";
        try (PrintWriter out = new PrintWriter(new FileWriter(jsonPath))) {
            out.write(object.toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
        File inputJson = new File(jsonPath);
        // Generated class will be in the following directory, can move to model package later.
        File outputPojoDirectory = new File(basePath + File.separator + "convertedPojo");
        outputPojoDirectory.mkdirs();
        try {
            JsonUtility.convertJsonToJavaClass(inputJson.toURI().toURL(), outputPojoDirectory, packageName, inputJson.getName().replace(".json", ""));
        } catch (IOException e) {
            System.out.println("Encountered issue while converting to pojo: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
